In [2]:
import pandas as pd

In [3]:
for period in  ["1221", "0322", "0622", "0922", "1222"]:
    yahoo_old = pd.read_excel(f"data/yahoo/adj_price_yahoo_comp_{period}.xlsx")
    yahoo_new = pd.read_excel(f"data/yahoo/adj_price_yahoo_comp_{period}_new.xlsx")
    yahoo_old.set_index(yahoo_old.Date, drop=True, inplace=True)
    yahoo_new.set_index(yahoo_new.Date, drop=True, inplace=True)
    yahoo_new = yahoo_new.reindex(yahoo_old.index)
    common = yahoo_new.columns.intersection(yahoo_old.columns)

    y1 = yahoo_new[common].copy()
    y2 = yahoo_old[common].copy()
    diff = y1.compare(y2)        # default shows self vs other
    print(period)
    print(diff)

1221
                   ABT                    AES                    IBM  \
                  self       other       self      other        self
Date
2019-12-31   78.127106   78.826752  16.206373  16.426224   99.540375
2020-01-02   78.208046   78.908417  16.312243  16.533527  100.565201
2020-01-03   77.254616   77.946449  16.124933  16.343674   99.763161
2020-01-06   77.659355   78.354836  16.312243  16.533527   99.584938
2020-01-07   77.227638   77.919220  16.369255  16.591312   99.651772
...                ...         ...        ...        ...         ...
2021-12-27  131.241318  132.416672  20.428858  20.705990  113.015038
2021-12-28  130.322800  131.489944  20.489273  20.767221  113.882278
2021-12-29  130.990829  132.163925  20.523798  20.802214  114.500511
2021-12-30  130.814545  131.986053  20.860397  21.143377  114.981361
2021-12-31  130.573349  131.742661  20.972593  21.257101  114.766678

                               ARE                     APD              ...  \
                 other        self       other        self       other  ...
Date                                                                    ...
2019-12-31  100.213371  129.915649  134.397232  204.630936  207.298492  ...
2020-01-02  101.245125  128.428146  132.858444  201.278320  203.902161  ...
2020-01-03  100.437675  129.159851  133.615372  196.802368  199.367874  ...
2020-01-06  100.258232  129.473404  133.939743  196.715302  199.279617  ...
2020-01-07  100.325516  125.236168  129.556290  197.551300  200.126495  ...
...                ...         ...         ...         ...         ...  ...
2021-12-27  113.779160  185.118988  191.504868  273.364563  276.928101  ...
2021-12-28  114.652260  186.708603  193.149277  274.965576  278.549957  ...
2021-12-29  115.274651  188.037476  194.524033  276.240936  279.841949  ...
2021-12-30  115.758743  188.663071  195.171219  274.875153  278.458282  ...
2021-12-31  115.542633  188.494019  194.996292  276.574951  280.180298  ...

                 PBCT                    DFS                    INFO  \
                 self      other        self       other        self
Date
2019-12-31  15.104652  15.246179   80.532812   74.634789   73.990261
2020-01-02  14.979525  15.119880   80.988551   75.057121   74.422321
2020-01-03  14.854397  14.993580   79.640324   73.807655   74.451780
2020-01-06  14.782896  14.921409   78.235130   72.505371   74.864201
2020-01-07  14.657769  14.795109   77.371126   71.704628   75.050772
...               ...        ...         ...         ...         ...
2021-12-27  17.654580  17.820000  115.664735  107.193718  134.330082
2021-12-28  17.733838  17.900000  115.614931  107.147552  133.072328
2021-12-29  17.714023  17.880000  115.316107  106.870628  133.202097
2021-12-30  17.535694  17.700000  115.375872  106.926018  132.094076
2021-12-31  17.654580  17.820000  115.106930  106.676773  132.683024

                             NLSN                   WRK
                 other       self      other       self      other
Date
2019-12-31   74.122410  19.733489  19.801653  40.637742  40.853213
2020-01-02   74.555242  19.558512  19.626072  41.149147  41.367329
2020-01-03   74.584753  19.519628  19.587054  40.419921  40.634237
2020-01-06   74.997910  19.918186  19.986988  39.804342  40.015393
2020-01-07   75.184815  19.791814  19.860180  39.359230  39.567922
...                ...        ...        ...        ...        ...
2021-12-27  134.570000  21.136988  21.210000  43.529198  43.760000
2021-12-28  133.310000  21.117057  21.190000  43.956930  44.190000
2021-12-29  133.440000  20.788193  20.860000  44.046456  44.280000
2021-12-30  132.330000  20.628744  20.700000  43.986772  44.220000
2021-12-31  132.920000  20.439398  20.510000  44.126034  44.360000

[506 rows x 822 columns]
0322
                   ABT                    AES                    IBM  \
                  self       other       self      other        self
Date
2021-03-31  109.931770  110.916252  22.733366  23.041763  105.542770
2021-04-01  109.106171  110.083267  22.953836  23.265217  105.519028
2021-04-05  109.950119  110.934769  23.182783  23.497269  107.657448
2021-04-06  110.051018  111.036598  23.589792  23.909803  106.303116
2021-04-07  110.179443  111.166145  22.970791  23.282410  106.865433
...                ...         ...        ...        ...         ...
2022-03-28  111.714905  112.715363  21.427515  21.718189  114.246010
2022-03-29  111.901115  112.903252  22.122931  22.423042  114.654434
2022-03-30  112.078011  113.081726  22.122931  22.423042  114.819550
2022-03-31  110.197327  111.184196  22.366327  22.669741  112.986015
2022-04-01  110.402153  111.390854  22.792267  23.101458  113.098946

                               ARE                     APD              ...  \
                 other        self       other        self       other  ...
Date                                                                    ...
2021-03-31  106.256386  136.544998  141.255249  251.694748  254.975769  ...
2021-04-01  106.232452  141.049377  145.915024  254.879669  258.202209  ...
2021-04-05  108.385338  141.855515  146.748978  259.003937  262.380249  ...
2021-04-06  107.021843  142.113129  147.015488  257.670959  261.029907  ...
2021-04-07  107.587959  141.282089  146.155746  252.723648  256.018036  ...
...                ...         ...         ...         ...         ...  ...
2022-03-28  115.018456  166.293350  172.029831  225.715897  228.658310  ...
2022-03-29  115.429634  171.315125  177.224838  229.379227  232.369339  ...
2022-03-30  115.595879  171.816803  177.743774  230.124634  233.124451  ...
2022-03-31  113.749908  171.111099  177.013718  228.633377  231.613785  ...
2022-04-01  113.863625  175.124222  181.165314  227.791733  230.761139  ...

                  MRO                   SBNY                     DFS  \
                 self      other        self       other        self
Date
2021-03-31  10.496595  10.526693  223.712173  224.219519   92.956053
2021-04-01  11.587533  11.620759  222.623790  223.128667   95.118732
2021-04-05  10.997837  11.029372  225.780101  226.292136   96.782331
2021-04-06  10.948695  10.980089  221.248470  221.750228   96.801902
2021-04-07  10.752130  10.782960  221.337519  221.839479   96.684472
...               ...        ...         ...         ...         ...
2022-03-28  25.217691  25.290000  302.753301  303.439900  110.640582
2022-03-29  24.928520  25.000000  315.354923  316.070100  113.643229
2022-03-30  25.427091  25.500000  305.776545  306.470000  112.639033
2022-03-31  25.038206  25.110000  292.825915  293.490000  109.556845
2022-04-01  25.676376  25.750000  289.164319  289.820100  109.487248

                             NLSN                   WRK
                 other       self      other       self      other
Date
2021-03-31   86.646042  24.816170  24.874561  50.826995  51.075757
2021-04-01   88.661911  24.993780  25.052589  50.963706  51.213136
2021-04-05   90.212585  25.191126  25.250399  51.627728  51.880409
2021-04-06   90.230827  25.220727  25.280070  52.369870  52.626183
2021-04-07   90.121361  24.756966  24.815218  51.549608  51.801906
...                ...        ...        ...        ...        ...
2022-03-28  103.130104  22.157864  22.210000  47.278605  47.510000
2022-03-29  105.928932  26.657277  26.720000  47.756267  47.990000
2022-03-30  104.992912  26.966549  27.030000  47.109433  47.340000
2022-03-31  102.119942  27.176056  27.240000  46.800943  47.030000
2022-04-01  102.055077  27.265845  27.330000  46.960164  47.190000

[255 rows x 824 columns]
0622
                   ABT                    AES                    IBM  \
                  self       other       self      other        self
Date
2021-06-30  106.735497  107.691368  22.225883  22.527390  117.397453
2021-07-01  107.867966  108.833984  22.447542  22.752060  117.597649
2021-07-02  108.678169  109.651428  22.302612  22.605162  112.135818
2021-07-06  109.396309  110.376007  22.166203  22.466900  111.142746
2021-07-07  110.363029  111.351387  22.157679  22.458261  111.975655
...                ...         ...        ...        ...         ...
2022-06-27  101.962112  102.875206  18.786530  19.041374  125.596992
2022-06-28   99.989777  100.885231  18.558809  18.810572  124.770195
2022-06-29  101.980782  102.894066  17.831873  18.073776  123.758774
2022-06-30  101.560165  102.469673  18.401159  18.650785  124.180916
2022-07-01  103.027702  103.950371  18.812801  19.068008  124.119385

                               ARE                     APD              ...  \
                 other        self       other        self       other  ...
Date                                                                    ...
2021-06-30  118.191185  152.129272  157.377151  258.712860  262.085358  ...
2021-07-01  118.392738  152.396820  157.653915  259.720001  263.105713  ...
2021-07-02  112.893997  153.843369  159.150375  261.491669  264.900421  ...
2021-07-06  111.894211  155.875244  161.252319  257.849518  261.210815  ...
2021-07-07  112.732735  156.301666  161.693466  261.509705  264.918640  ...
...                ...         ...         ...         ...         ...  ...
2022-06-27  126.446152  123.846153  128.118378  225.220917  228.156860  ...
2022-06-28  125.613831  122.859848  127.098045  221.863388  224.755585  ...
2022-06-29  124.595512  123.905708  128.179962  222.430618  225.330154  ...
2022-06-30  125.020546  124.325760  128.614502  221.481979  224.369156  ...
2022-07-01  124.958542  126.983177  131.363632  223.572662  226.487091  ...

                  MRO                   SBNY                     DFS  \
                 self      other        self       other        self
Date
2021-06-30  13.384026  13.429960  242.834766  243.590462  115.534629
2021-07-01  13.924497  13.972286  247.055830  247.824662  116.902018
2021-07-02  13.610041  13.656751  245.217147  245.980256  117.400139
2021-07-06  12.981129  13.025681  238.406108  239.148022  115.026742
2021-07-07  12.705980  12.749587  238.327025  239.068693  115.554163
...               ...        ...         ...         ...         ...
2022-06-27  23.040923  23.120000  188.672855  189.260000   98.064515
2022-06-28  24.047469  24.130000  186.968160  187.550000   96.752083
2022-06-29  22.712052  22.790000  183.429173  184.000000   95.041945
2022-06-30  22.403112  22.480000  178.654033  179.210000   94.037735
2022-07-01  22.472873  22.550000  183.548801  184.120000   97.129904

                             NLSN                   WRK
                 other       self      other       self      other
Date
2021-06-30  108.312950  24.342599  24.395671  51.859074  52.172081
2021-07-01  109.594856  24.579414  24.633002  51.976005  52.289718
2021-07-02  110.061844  24.411670  24.464893  51.352371  51.662320
2021-07-06  107.836807  23.977509  24.029786  49.968683  50.270280
2021-07-07  108.331253  23.938040  23.990230  50.894390  51.201575
...                ...        ...        ...        ...        ...
2022-06-27   91.934822  23.887919  23.940000  40.744080  40.990000
2022-06-28   90.704414  23.608528  23.660000  40.078099  40.320000
2022-06-29   89.101189  23.508745  23.560000  39.968759  40.210000
2022-06-30   88.159775  23.169485  23.220000  39.600979  39.840000
2022-07-01   91.058647  23.568615  23.620000  39.889239  40.130000

[254 rows x 828 columns]
0922
                   ABT                    AES                    IBM  \
                  self       other       self      other        self
Date
2021-09-30  109.175087  110.152802  19.585485  19.851171  112.543869
2021-10-01  108.324821  109.294922  19.645536  19.912043  116.100105
2021-10-04  106.772171  107.728371  19.594063  19.859867  116.740036
2021-10-05  107.095642  108.054726  20.057320  20.329412  115.962379
2021-10-06  107.659409  108.623535  20.091639  20.364193  115.322403
...                ...         ...        ...        ...         ...
2022-10-26   92.842636   93.674088  22.449038  22.753574  120.241531
2022-10-27   91.437073   92.255913  22.731310  23.039669  120.027794
2022-10-28   93.851997   94.692474  23.339945  23.656565  123.358658
2022-10-31   93.333168   94.169014  23.213932  23.528845  123.162735
2022-11-01   93.682198   94.521164  23.373663  23.690741  123.082611

                               ARE                     APD              ...  \
                 other        self       other        self       other  ...
Date                                                                    ...
2021-09-30  113.304756  160.702774  166.246368  231.657028  234.676895  ...
2021-10-01  116.885056  163.192337  168.821808  232.851028  235.886429  ...
2021-10-04  117.529327  163.284836  168.917542  231.548538  234.566925  ...
2021-10-05  116.746399  161.594269  167.168671  232.480164  235.510727  ...
2021-10-06  116.102127  164.159531  169.822418  235.854034  238.928558  ...
...                ...         ...         ...         ...         ...  ...
2022-10-26  121.054497  121.111549  125.289429  233.744217  236.791214  ...
2022-10-27  120.839310  122.831825  127.069023  230.998840  234.010071  ...
2022-10-28  124.192726  125.969818  130.315323  235.988708  239.064972  ...
2022-10-31  123.995438  125.606758  129.939697  232.241653  235.269119  ...
2022-11-01  123.914787  125.139946  129.456787  233.836945  236.885162  ...

                 JNPR                    PXD                    MRO  \
                 self      other        self       other       self
Date
2021-09-30  26.624343  24.920218  147.314518  150.826693  13.453602
2021-10-01  27.088721  25.354870  154.542670  158.227174  14.014579
2021-10-04  26.885556  25.164713  158.338114  162.113106  14.595239
2021-10-05  27.108070  25.372986  160.983423  164.821483  15.136532
2021-10-06  27.166118  25.427315  160.841868  164.676553  14.851123
...               ...        ...         ...         ...        ...
2022-10-26  29.802322  27.894787  259.307757  265.490000  30.096425
2022-10-27  30.080477  28.155140  259.649606  265.840000  30.435483
2022-10-28  30.626853  28.666542  251.318237  257.310000  30.076480
2022-10-31  30.398368  28.452682  250.439195  256.410000  30.365677
2022-11-01  30.706326  28.740931  247.040231  252.930000  30.844348

                              DFS                    WRK
                other        self       other       self      other
Date
2021-09-30  13.490961  119.778729  112.918266  48.400926  48.780297
2021-10-01  14.053496  124.010228  116.907410  49.469379  49.857125
2021-10-04  14.635769  122.830478  115.795242  49.799628  50.189963
2021-10-05  15.178565  124.292978  117.173965  50.149303  50.542379
2021-10-06  14.892363  123.327728  116.264000  49.139129  49.524287
...               ...         ...         ...        ...        ...
2022-10-26  30.180000  101.652846   96.462700  33.090632  33.350000
2022-10-27  30.520000  102.239573   97.019463  33.437910  33.700000
2022-10-28  30.160000  105.053871   99.690079  34.003477  34.270000
2022-10-31  30.450000  103.880418   98.576538  33.795110  34.060000
2022-11-01  30.930000  103.313581   98.038628  33.785188  34.050000

[275 rows x 822 columns]
1222
           Date            AMZN                    ABT                    AES  \
           self      other self      other        self       other       self
Date
2019-12-02  NaT 2019-12-02  NaN  89.080002         NaN   76.694099        NaN
2019-12-03  NaT 2019-12-03  NaN  88.498001         NaN   76.557953        NaN
2019-12-04  NaT 2019-12-04  NaN  88.034500         NaN   77.302124        NaN
2019-12-05  NaT 2019-12-05  NaN  87.024002         NaN   77.356575        NaN
2019-12-06  NaT 2019-12-06  NaN  87.580002         NaN   77.574402        NaN
...         ...        ...  ...        ...         ...         ...        ...
2022-12-23  NaT        NaT  NaN        NaN  102.049553  102.963448  25.450140
2022-12-27  NaT        NaT  NaN        NaN  102.417435  103.334641  25.574373
2022-12-28  NaT        NaT  NaN        NaN  101.719368  102.630325  25.130680
2022-12-29  NaT        NaT  NaN        NaN  104.058846  104.990730  25.565496
2022-12-30  NaT        NaT  NaN        NaN  103.568298  104.495804  25.521132

                              IBM              ... SBNY                DFS  \
                other        self       other  ... self       other   self
Date                                           ...
2019-12-02  15.617292         NaN   99.368546  ...  NaN  116.877836    NaN
2019-12-03  15.551257         NaN   98.777924  ...  NaN  117.922586    NaN
2019-12-04  15.600784         NaN   98.680733  ...  NaN  119.580768    NaN
2019-12-05  15.526492         NaN   98.620918  ...  NaN  120.088766    NaN
2019-12-06  15.452205         NaN   99.600311  ...  NaN  121.028082    NaN
...               ...         ...         ...  ...  ...         ...    ...
2022-12-23  25.795387  127.659340  128.522461  ...  NaN         NaN  97.60
2022-12-27  25.921307  128.353287  129.221085  ...  NaN         NaN  96.75
2022-12-28  25.471594  126.190323  127.043526  ...  NaN         NaN  95.28
2022-12-29  25.912312  127.127647  127.987122  ...  NaN         NaN  97.45
2022-12-30  25.867342  126.974396  127.832901  ...  NaN         NaN  97.83

                        PARA            CTLT         WRK
                other   self      other self  other self      other
Date
2019-12-02  73.966057    NaN  34.264893  NaN  51.43  NaN  37.551550
2019-12-03  72.998146    NaN  33.817886  NaN  51.36  NaN  36.715005
2019-12-04  73.587662    NaN  35.047157  NaN  51.78  NaN  36.603466
2019-12-05  73.147720    NaN  35.124527  NaN  51.60  NaN  37.161162
2019-12-06  74.186028    NaN  34.144539  NaN  52.05  NaN  38.323029
...               ...    ...        ...  ...    ...  ...        ...
2022-12-23  92.616776  16.66  15.863954  NaN    NaN  NaN        NaN
2022-12-27  91.810173  16.52  15.730645  NaN    NaN  NaN        NaN
2022-12-28  90.415222  16.11  15.340235  NaN    NaN  NaN        NaN
2022-12-29  92.474434  16.77  15.968699  NaN    NaN  NaN        NaN
2022-12-30  92.835037  16.88  16.073444  NaN    NaN  NaN        NaN

[777 rows x 1000 columns]

In [4]:
for period in  ["1221", "0322", "0622", "0922", "1222"]:
    stocks_with_missing_prices_excel = pd.read_excel(f"data/stocks_with_missing_prices/stocks_with_missing_prices_{period}.xlsx")
    print(stocks_with_missing_prices_excel)

  symbol  period start_period first_valid  nan_count  total_rows  nan_ratio
0   CARR    1221   2019-11-01  2020-03-19         94         608   0.154605
1   OTIS    1221   2019-11-01  2020-03-19         94         608   0.154605
2    OGN    1221   2019-11-01  2021-05-14        385         608   0.633224
  symbol  period start_period first_valid  nan_count  total_rows  nan_ratio
0   CARR     322   2020-02-01  2020-03-19         32         608   0.052632
1   OTIS     322   2020-02-01  2020-03-19         32         608   0.052632
2    OGN     322   2020-02-01  2021-05-14        323         608   0.531250
3    CEG     322   2020-02-01  2022-01-19        495         608   0.814145
  symbol  period start_period first_valid  nan_count  total_rows  nan_ratio
0    OGN     622   2020-05-01  2021-05-14        261         610   0.427869
1    CEG     622   2020-05-01  2022-01-19        433         610   0.709836
  symbol  period start_period first_valid  nan_count  total_rows  nan_ratio
0    OGN     922   2020-08-01  2021-05-14        197         609   0.323481
1    CEG     922   2020-08-01  2022-01-19        369         609   0.605911
   symbol  period start_period first_valid  nan_count  total_rows  nan_ratio
0     OGN    1222   2020-11-01  2021-05-14        133         607   0.219110
1     CEG    1222   2020-11-01  2022-01-19        305         607   0.502471
2     HES    1222   2020-11-01  2020-11-02         62         607   0.102142
3    ANSS    1222   2020-11-01  2020-11-02         62         607   0.102142
4    DISH    1222   2020-11-01  2020-11-02         62         607   0.102142
5    JNPR    1222   2020-11-01  2020-11-02         62         607   0.102142
6    ATVI    1222   2020-11-01  2020-11-02         62         607   0.102142
7     PXD    1222   2020-11-01  2020-11-02         62         607   0.102142
8   SIVBQ    1222   2020-11-01  2020-11-02         62         607   0.102142
9     MRO    1222   2020-11-01  2020-11-02         62         607   0.102142
10   SBNY    1222   2020-11-01  2020-11-02         62         607   0.102142
11    DFS    1222   2020-11-01  2020-11-02         62         607   0.102142
12   PARA    1222   2020-11-01  2020-11-02         62         607   0.102142
13   CTLT    1222   2020-11-01  2020-11-02         62         607   0.102142
14    WRK    1222   2020-11-01  2020-11-02         62         607   0.102142

In [8]:
y2.index

DatetimeIndex(['2019-12-02', '2019-12-03', '2019-12-04', '2019-12-05',
               '2019-12-06', '2019-12-09', '2019-12-10', '2019-12-11',
               '2019-12-12', '2019-12-13',
               ...
               '2022-12-16', '2022-12-19', '2022-12-20', '2022-12-21',
               '2022-12-22', '2022-12-23', '2022-12-27', '2022-12-28',
               '2022-12-29', '2022-12-30'],
              dtype='datetime64[ns]', name='Date', length=777, freq=None)

In [17]:
import pandas as pd
yahoo_new = pd.read_excel(f"data/yahoo/adj_price_yahoo_comp_{period}_new.xlsx")
yahoo_new

,Date,AMZN,ABT,AES,IBM,AMD,ADBE,ARE,APD,ALK,...,JNPR,ATVI,PXD,SIVBQ,MRO,SBNY,DFS,PARA,CTLT,WRK
0,2020-11-02,150.223999,98.198082,16.847340,86.984909,74.699997,444.940002,127.123856,253.858719,38.270000,...,18.432143,75.582593,71.409593,306.98,4.017853,79.112980,64.363175,27.630528,88.53,37.312565
1,2020-11-03,152.420502,100.098442,17.074778,87.947899,76.580002,454.019989,127.804901,255.939636,38.560001,...,18.835083,75.444091,70.892133,310.57,4.008171,78.809340,66.422107,28.125263,95.51,37.932692
2,2020-11-04,162.057999,101.898331,16.796801,86.206825,81.349998,487.230011,130.176407,256.161011,37.799999,...,18.778858,78.520817,72.013298,296.56,4.134032,74.646530,64.995219,27.789216,101.51,36.740140
3,2020-11-05,166.100006,103.725609,17.664436,88.417839,83.000000,496.470001,129.971252,268.602020,39.180000,...,19.219281,79.282579,68.632554,312.67,4.153395,76.830780,65.598534,29.208081,102.48,37.427050
4,2020-11-06,165.568497,104.538742,17.192713,87.855453,85.879997,494.630005,128.929108,271.594971,38.259998,...,19.294246,77.966809,66.700700,313.37,3.998490,74.450633,65.033525,27.350488,103.31,37.226701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,2023-03-27,98.040001,93.300896,20.181513,117.969597,96.610001,373.149994,103.528473,251.907028,38.990002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,2023-03-28,97.239998,92.021645,20.476198,117.996971,94.559998,373.399994,103.301804,255.030289,39.810001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,2023-03-29,100.250000,93.452530,20.949478,118.334526,96.089996,379.160004,107.259857,257.631561,40.630001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,2023-03-30,102.000000,93.888420,21.047709,117.887482,97.879997,381.899994,109.161697,260.792145,40.980000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,2023-03-31,103.290001,95.954178,21.503134,119.593506,98.010002,385.369995,110.579254,269.461121,41.959999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
yahoo_new.loc[:, ['Date','ANSS']]

          Date      ANSS
0   2020-11-02  311.2300
1   2020-11-03  315.9099
2   2020-11-04  329.2500
3   2020-11-05  328.3501
4   2020-11-06  336.8000
..         ...       ...
602 2023-03-27       NaN
603 2023-03-28       NaN
604 2023-03-29       NaN
605 2023-03-30       NaN
606 2023-03-31       NaN

[607 rows x 2 columns]

In [ ]:
# This is DEC 22 so for testing in the 3 months after I need January, February, March 2023 but here I only have it until febr. 22
# so i should extract again price_div

In [2]:
import pandas as pd

# ---------- 1) PRICE SHEET ----------
price_div_old = pd.read_excel("data/lseg/prices_dividends/price_div_comp_1222.xlsm",
                              sheet_name='CLOSE PRICE', header=4)

price_div_next_3m = pd.read_excel("data/lseg/prices_dividends/price_div_comp_1222_next3m.xlsm",
                                  sheet_name='CLOSE PRICE', header=4)

price_div_next_3m = price_div_next_3m.loc[
    (price_div_next_3m['Code'] > "2023") &
    (price_div_next_3m['Code'] <= "2023-03-31")
]

price_div = pd.concat([price_div_old, price_div_next_3m], axis=0)


# ---------- 2) DIV RATE SHEET ----------
div_rate_old = pd.read_excel("data/lseg/prices_dividends/price_div_comp_1222.xlsm",
                             sheet_name='DIV RATE', header=4)

div_rate_next_3m = pd.read_excel("data/lseg/prices_dividends/price_div_comp_1222_next3m.xlsm",
                                 sheet_name='DIV RATE', header=4)

div_rate_next_3m = div_rate_next_3m.loc[
    (div_rate_next_3m['Code'] > "2023") &
    (div_rate_next_3m['Code'] <= "2023-03-31")
]

div_rate = pd.concat([div_rate_old, div_rate_next_3m], axis=0)


# ---------- 3) DIV DATE SHEET ----------
div_date_old = pd.read_excel("data/lseg/prices_dividends/price_div_comp_1222.xlsm",
                             sheet_name='DIV DATE', header=4)

div_date_next_3m = pd.read_excel("data/lseg/prices_dividends/price_div_comp_1222_next3m.xlsm",
                                 sheet_name='DIV DATE', header=4)

div_date_next_3m = div_date_next_3m.loc[
    (div_date_next_3m['Code'] > "2023") &
    (div_date_next_3m['Code'] <= "2023-03-31")
]

div_date = pd.concat([div_date_old, div_date_next_3m], axis=0)


price_div.to_excel("data/lseg/prices_dividends/price_1222_new.xlsx")
div_rate.to_excel("data/lseg/prices_dividends/div_rate_1222_new.xlsx")
div_date.to_excel("data/lseg/prices_dividends/div_date_1222_new.xlsx")

In [6]:
div_date_old

,Code,Unnamed: 1,916328(XDDE),545101(XDDE),906187(XDDE),Unnamed: 5,Unnamed: 6,891631(XDDE),905271(XDDE),921794(XDDE),...,Unnamed: 494,9174A0(XDDE),905277(XDDE),916091(XDDE),Unnamed: 498,902335(XDDE),Unnamed: 500,9373MH(XDDE),699786(XDDE),Unnamed: 503
0,2019-01-01,"$$ER: 1929,NO DATA FOUND",NaT,NaT,NaT,"$$ER: 1929,NO DATA FOUND","$$ER: 1929,NO DATA FOUND",NaT,NaT,NaT,...,"$$ER: E100,INVALID CODE OR EXPRESSION ENTERED",NaT,NaT,NaT,"$$ER: 1929,NO DATA FOUND",NaT,"$$ER: 1929,NO DATA FOUND",NaT,NaT,"$$ER: E100,INVALID CODE OR EXPRESSION ENTERED"
1,2019-01-02,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
2,2019-01-03,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
3,2019-01-04,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
4,2019-01-07,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,2022-12-26,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
1040,2022-12-27,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
1041,2022-12-28,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
1042,2022-12-29,NaN,NaT,NaT,NaT,NaN,NaN,2022-12-29,NaT,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN
1043,2022-12-30,NaN,NaT,NaT,NaT,NaN,NaN,NaT,2022-12-30,NaT,...,NaN,NaT,NaT,NaT,NaN,NaT,NaN,NaT,NaT,NaN

In [7]:
div_date_next_3m

,Code,Unnamed: 1,916328(XDDE),545101(XDDE),906187(XDDE),Unnamed: 5,Unnamed: 6,891631(XDDE),905271(XDDE),Unnamed: 9,...,Unnamed: 494,9174A0(XDDE),905277(XDDE),Unnamed: 497,871997(XDDE),902335(XDDE),Unnamed: 500,9373MH(XDDE),699786(XDDE),Unnamed: 503
1,2023-01-02,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
2,2023-01-03,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
3,2023-01-04,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
4,2023-01-05,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
5,2023-01-06,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2023-03-27,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
62,2023-03-28,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
63,2023-03-29,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
64,2023-03-30,NaN,NaT,NaT,NaT,NaN,NaN,2023-03-30,NaT,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN
65,2023-03-31,NaN,NaT,NaT,NaT,NaN,NaN,NaT,2023-03-31,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,NaN,NaT,NaT,NaN

In [4]:
div_rate

,Code,Unnamed: 1,916328(DDE),545101(DDE),906187(DDE),Unnamed: 5,Unnamed: 6,891631(DDE),905271(DDE),921794(DDE),...,86831C(DDE),50394K(DDE),Unnamed: 416,696306(DDE),8733L2(DDE),8858FM(DDE),Unnamed: 460,29026M(DDE),Unnamed: 497,871997(DDE)
0,2019-01-01,"$$ER: 1929,NO DATA FOUND",NaN,NaN,NaN,"$$ER: 1929,NO DATA FOUND","$$ER: 1929,NO DATA FOUND",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2023-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2023-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2023-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,2023-03-30,NaN,NaN,NaN,NaN,NaN,NaN,1.21,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,2023-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.75,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN